# generate_modernranking.ps1 - Regenerate modernranking.cpp's kTable
# from the wikipedia-top.tsv corpus fixture. Every distinct reading in
# the top-N frequency band becomes an override entry mapping the reading
# to its HIGHEST-frequency expected kanji.
#
# Why: probe_skk_coverage.ps1 measured raw-SKK top-correct at 74.7% on
# the 100+ band, but the corpus regression test (which runs the actual
# bunsetsu SplitMecab pipeline) came in at 63.3% because the bunsetsu
# path's ReadsAs filter rejects perfectly good SKK tops (SKK top「年」
# for reading「ねん」 gets filtered because MeCab reads 年 primarily as
# とし). Front-inserting the corpus-preferred surface via ModernRanking
# bypasses that filter entirely for the readings that matter most.
#
# Usage:
#   .\generate_modernranking.ps1 -MinCount 100
#
# Overwrites: src/GenerativeIME.Tsf/modernranking.cpp
# Preserves: header, GetPreferred / PromoteToTop implementations.

[CmdletBinding()]
param(
    [string]$Golden = (Join-Path $PSScriptRoot '..\..\corpus\goldens\wikipedia-top.tsv'),
    [string]$OutCpp = (Join-Path $PSScriptRoot '..\..\src\GenerativeIME.Tsf\modernranking.cpp'),
    [int]$MinCount = 100
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path $Golden)) { Write-Error "Golden not found: $Golden"; return }

Write-Host ("[read] {0} (min count = {1})" -f $Golden, $MinCount)

# Read golden, dedupe by reading keeping the HIGHEST-frequency expected.
# Golden is already sorted by count descending, so first hit per reading
# wins.
$best = @{}
foreach ($line in Get-Content $Golden -Encoding UTF8) {
    if ($line.Length -eq 0 -or $line[0] -eq '#') { continue }
    $p = $line -split "`t"
    if ($p.Count -lt 3) { continue }
    $count = [int]$p[2]
    if ($count -lt $MinCount) { break }
    $reading = $p[0]
    $expected = $p[1]
    if (-not $best.ContainsKey($reading)) {
        $best[$reading] = @{ Expected = $expected; Count = $count }
    }
}

Write-Host ("[dedupe] {0} unique readings above threshold" -f $best.Count)

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('#include "modernranking.h"')
[void]$sb.AppendLine('#include <unordered_map>')
[void]$sb.AppendLine('#include <algorithm>')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('// AUTO-GENERATED by scripts/mine/generate_modernranking.ps1')
[void]$sb.AppendLine('// Source: corpus/goldens/wikipedia-top.tsv')
[void]$sb.AppendLine(("// Filter: count >= {0} (dedupe by reading, keep highest-freq expected)" -f $MinCount))
[void]$sb.AppendLine('// Do NOT hand-edit; re-run the generator against an updated corpus instead.')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('namespace modernranking')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    static const Entry kTable[] = {')

# Sort entries by count descending so the file is readable / greppable.
$sorted = $best.Keys | Sort-Object { -$best[$_].Count }
foreach ($reading in $sorted) {
    $expected = $best[$reading].Expected
    $count = $best[$reading].Count
    [void]$sb.AppendLine(("        {{ L`"{0}`", L`"{1}`" }},  // {2}x" -f $reading, $expected, $count))
}

[void]$sb.AppendLine('    };')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    static const std::unordered_map<std::wstring, std::wstring>& Index()')
[void]$sb.AppendLine('    {')
[void]$sb.AppendLine('        static const auto* m = []() {')
[void]$sb.AppendLine('            auto* out = new std::unordered_map<std::wstring, std::wstring>();')
[void]$sb.AppendLine('            out->reserve(sizeof(kTable) / sizeof(kTable[0]));')
[void]$sb.AppendLine('            for (const auto& e : kTable) {')
[void]$sb.AppendLine('                (*out)[e.reading] = e.preferred;')
[void]$sb.AppendLine('            }')
[void]$sb.AppendLine('            return out;')
[void]$sb.AppendLine('        }();')
[void]$sb.AppendLine('        return *m;')
[void]$sb.AppendLine('    }')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    std::wstring GetPreferred(const std::wstring& reading)')
[void]$sb.AppendLine('    {')
[void]$sb.AppendLine('        const auto& m = Index();')
[void]$sb.AppendLine('        auto it = m.find(reading);')
[void]$sb.AppendLine('        return (it != m.end()) ? it->second : std::wstring{};')
[void]$sb.AppendLine('    }')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    std::vector<std::wstring> PromoteToTop(const std::wstring& reading,')
[void]$sb.AppendLine('                                           std::vector<std::wstring> candidates)')
[void]$sb.AppendLine('    {')
[void]$sb.AppendLine('        std::wstring preferred = GetPreferred(reading);')
[void]$sb.AppendLine('        if (preferred.empty()) return candidates;')
[void]$sb.AppendLine('        if (!candidates.empty() && candidates[0] == preferred) return candidates;')
[void]$sb.AppendLine('        auto it = std::find(candidates.begin(), candidates.end(), preferred);')
[void]$sb.AppendLine('        if (it != candidates.end()) candidates.erase(it);')
[void]$sb.AppendLine('        candidates.insert(candidates.begin(), preferred);')
[void]$sb.AppendLine('        return candidates;')
[void]$sb.AppendLine('    }')
[void]$sb.AppendLine('}')

# Write as UTF-8 without BOM (matches other .cpp files in the tree)
[System.IO.File]::WriteAllText($OutCpp, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host ("[write] {0}" -f $OutCpp)
Write-Host ("[write] {0} entries generated" -f $best.Count)
