#pragma once

#include <string>
#include <string_view>
#include <vector>

// Reading -> symbol/unit lookup. Bypasses the LLM for things MeCab can't
// give a reading for (Unicode-compat symbols like ℃, ㎢, →) and for things
// users say by visual name ("やじるし" -> "→"). Hits from here go straight
// into the candidate list without going through Ollama, so simple symbol
// input stays instant.
namespace symbols
{
    // Direct exact-match lookup. Empty vector if no hit.
    std::vector<std::wstring> Lookup(std::wstring_view reading);

    // Longest-prefix segmentation: combines multiple keys ("ろーま5うえつき2" -> "Ⅴ²").
    // Returns empty vector if no segmentation works.
    std::vector<std::wstring> SegmentedLookup(std::wstring_view reading);

    // Top-level entry the IME calls: tries Lookup, then SegmentedLookup,
    // then choonpu-expanded variants. Returns first that produces results.
    std::vector<std::wstring> LookupAll(std::wstring_view reading);

    // Full-width <-> half-width punctuation pair lookup for a single-char
    // composition. Given "！" returns {"！", "!"}; given "!" returns
    // {"!", "！"} — the typed form stays at index 0 so a bare Enter keeps
    // what the user got, while ↓/Space picks the other form. Empty for
    // anything that isn't a known punctuation pair.
    //
    // 例外: 開き括弧「（｛＜［ 等は「ペア」(「」など) を先頭候補にする。
    // 括弧は単独より対で使うのが常態で、Space+Enter で「」を得られる方が
    // 期待に沿うため。単独が欲しいときは ↓ で index 1 を選ぶ。
    std::vector<std::wstring> PunctPairs(std::wstring_view typed);

    // Single ASCII letter -> glyph variants (typed form first, then the
    // full-width / opposite-case / regional-indicator 🇼 / circled Ⓦ
    // forms). Same idea as the digit entries ("5" → Ⅴ/⑤/五) but generated
    // arithmetically for all 26 letters instead of hand-listed. Empty for
    // anything that isn't exactly one ASCII letter.
    std::vector<std::wstring> LetterVariants(std::wstring_view typed);

    // Two ASCII letters -> country flag emoji generated by placing the
    // corresponding pair of REGIONAL INDICATOR SYMBOL LETTERs adjacent
    // (jp → 🇯🇵, us → 🇺🇸, gb → 🇬🇧, etc). Case-insensitive; both letters
    // must be a-z or A-Z. Returns a single-element vector containing the
    // surrogate-pair-encoded flag (4 UTF-16 code units), or empty when the
    // input isn't exactly two ASCII letters. Fonts render any adjacent
    // indicator pair as the flag — nothing here validates it's a real
    // ISO 3166-1 alpha-2 code, so「XX」also returns a flag glyph even
    // though no country has that code (the shaper falls back to two
    // boxed letters, which is the same visual you'd get pasting the raw
    // codepoints in yourself).
    std::vector<std::wstring> FlagFromIso2(std::wstring_view typed);

    // Acronym -> expansion lookup. Given an all-uppercase ASCII acronym key
    // ("IMF") returns the human-readable expansions ({"国際通貨基金",
    // "International Monetary Fund"}) to append behind the width/case forms
    // in the candidate window. Curated built-in table (国際機関・経済・IT の
    // 頻出略語); the long tail is meant to be covered by the LLM fallback.
    // Empty for anything not in the table. Key must already be uppercase
    // half-width ASCII.
    std::vector<std::wstring> AcronymExpansions(std::wstring_view upperAscii);

    // Width/case variants for a MULTI-char alphanumeric composition. Given
    // the full-width "ＩＭＥ" that Shift+alpha produces in 全角ひらがな mode,
    // returns {ＩＭＥ, IME, ime, ｉｍｅ} — the typed form stays at index 0 so a
    // bare Enter keeps it, while Space/↓ cycles to half-width / lower-case
    // forms. Every character must be an ASCII or full-width letter/digit and
    // at least one must be a letter; otherwise empty (so pure-kana or
    // punctuation compositions are left to the normal conversion path).
    std::vector<std::wstring> AsciiWidthCaseVariants(std::wstring_view typed);
}
